"""create tasks table

Revision ID: 10423be7b3de
Revises: 
Create Date: 2025-05-04 18:06:22.282932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10423be7b3de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tasks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('estimated_time', sa.String(length=20), nullable=False), # 1h, 1d, 1w
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('spent_time', sa.String(length=20), nullable=True), # 1h, 1d, 1w
        sa.Column('status', sa.String(length=50), nullable=True, default='todo'), # todo, in progress, done
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
